name: atcluster

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command: --cleanup --label-enable --interval 3600

  warrior:
    environment:
      - ATUSER
    image: atdr.meo.ws/archiveteam/usgovernment-grab
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command: --concurrent 3 ${ATUSER}
    deploy:
      replicas: 10
